name: BluestarQQ
version: '${project.version}'
main: me.lanzhi.bluestarqq.BluestarQQ
api-version: 1.18
author: lanzhi
depend:
  - BluestarBot
  - PlaceholderAPI
  - BluestarGameAPI
loadbefore:
  - BluestarGame
commands:
  qqreply:
  bluestarqq:
    aliases:
      - bsqq
    permission: bluestarqq.op
  bindqq:
    aliases:
      - bind
      - qqbind
permissions:
  bluestarqq.*:
    children:
      bluestarqq.op:
        default: false